spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: local

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

# JPA
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

  h2:
    console:
      enabled: true
      path: /h2
      datasource:
      url: jdbc:h2:mem:test

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

---
spring:
  config:
    activate:
      on-profile: prod

server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

# JPA
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

  h2:
    console:
      enabled: true
      path: /h2
      datasource:
      url: jdbc:h2:mem:test

  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

